include $(GOROOT)/src/Make.inc

TARG = feeder
GOFILES = feed.go rss.go atom.go channel.go image.go item.go cloud.go \
	enclosure.go source.go input.go category.go generator.go link.go\
	subtitle.go author.go content.go

include $(GOROOT)/src/Make.pkg
